'use strict';
const gallery=document.querySelector('#gallery'),filters=document.querySelector('#filters'),search=document.querySelector('#search'),viewer=document.querySelector('#viewer');
let selected='Alle',visible=CATALOG.slice(),index=0,viewerItems=CATALOG.slice();
const categories=['Alle',...new Set(CATALOG.map(s=>s[1]))];
function button(text,cls){const b=document.createElement('button');b.type='button';b.textContent=text;b.className=cls||'';return b;}
for(const category of categories){const b=button(category);b.setAttribute('aria-pressed',category===selected);b.addEventListener('click',()=>{selected=category;render();});filters.append(b);}
function open(id){viewerItems=visible.some(s=>s[0]===id)?visible:CATALOG;index=viewerItems.findIndex(s=>s[0]===id);show();if(!viewer.open)viewer.showModal();}
function show(){const [id,category,title,description]=viewerItems[index];document.querySelector('#viewer-img').src=`screens/${id}.png`;document.querySelector('#viewer-img').alt=title+' – Firmware-Vorschau';document.querySelector('#viewer-title').textContent=title;document.querySelector('#viewer-category').textContent=category;document.querySelector('#viewer-description').textContent=description;document.querySelector('#viewer-index').textContent=`${index+1} / ${viewerItems.length}`;document.querySelector('#download-screen').href=`screens/${id}.png`;}
function render(){const term=search.value.trim().toLocaleLowerCase('de');visible=CATALOG.filter(s=>(selected==='Alle'||s[1]===selected)&&s.join(' ').toLocaleLowerCase('de').includes(term));gallery.replaceChildren();for(const [id,category,title,description] of visible){const card=document.createElement('article');card.className='screen-card';const b=button('','screen-open');b.setAttribute('aria-label',`${title} vergrößern`);b.dataset.id=id;const img=new Image(368,448);img.src=`screens/${id}.png`;img.alt=title+' – Firmware-Vorschau';img.loading='lazy';b.append(img);const tag=document.createElement('p');tag.className='card-category';tag.textContent=category;const h=document.createElement('h3');h.textContent=title;const p=document.createElement('p');p.className='description';p.textContent=description;card.append(b,tag,h,p);gallery.append(card);}for(const b of filters.children)b.setAttribute('aria-pressed',b.textContent===selected);document.querySelector('#result-count').textContent=`${visible.length} von ${CATALOG.length} Ansichten`;document.querySelector('#empty').hidden=visible.length!==0;}
const animals=['Drache','Hund','Katze','Spinne','Schlange','Pikachu'];for(let i=0;i<animals.length;i++){const b=button('','animal-button');b.setAttribute('aria-label',animals[i]+' ansehen');b.dataset.id=`animal-${i}`;b.classList.add('screen-open');const crop=document.createElement('div');crop.className='animal-portrait';const img=new Image(368,448);img.src=`screens/animal-${i}.png`;img.alt='';img.loading='lazy';crop.append(img);const title=document.createElement('strong');title.textContent=animals[i];const sub=document.createElement('span');sub.textContent='Kennenlernen ↗';b.append(crop,title,sub);document.querySelector('#animal-grid').append(b);}
document.addEventListener('click',e=>{const b=e.target.closest('.screen-open');if(b)open(b.dataset.id);const a=e.target.closest('[data-filter-link]');if(a){selected=a.dataset.filterLink;search.value='';render();}});
search.addEventListener('input',render);document.querySelector('#close-viewer').addEventListener('click',()=>viewer.close());document.querySelector('#previous').addEventListener('click',()=>{index=(index+viewerItems.length-1)%viewerItems.length;show();});document.querySelector('#next').addEventListener('click',()=>{index=(index+1)%viewerItems.length;show();});viewer.addEventListener('click',e=>{if(e.target===viewer){const r=viewer.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)viewer.close();}});document.addEventListener('keydown',e=>{if(!viewer.open)return;if(e.key==='ArrowLeft'){e.preventDefault();document.querySelector('#previous').click();}if(e.key==='ArrowRight'){e.preventDefault();document.querySelector('#next').click();}});render();
